[main]
font=JetBrainsMono Nerd Font:size=9
pad=12x12

[colors]
background=222226
foreground=ffffff
selection-background=ffbe6f
selection-foreground=222226

# Adwaita/libadwaita dark palette
regular0=38383c
regular1=ff7b72
regular2=8fd694
regular3=ffbe6f
regular4=8cb4ff
regular5=d8a8ff
regular6=8bd5ca
regular7=ffffff

bright0=aaaaaa
bright1=ff8f87
bright2=a5e3a8
bright3=ffcf8a
bright4=a8c7ff
bright5=e5c6ff
bright6=a9e6dc
bright7=ffffff

[cursor]
style=beam
beam-thickness=2px
blink=no
color=222226 ffbe6f
