#!/bin/sh
set -eu

config_dir=${XDG_CONFIG_HOME:-"$HOME/.config"}
if [ -r "$config_dir/nnn/env" ]; then
    . "$config_dir/nnn/env"
fi

export EDITOR="${EDITOR:-micro}"
export VISUAL="${VISUAL:-$EDITOR}"

exec nnn "$@"
