#!/bin/sh
set -eu

config_dir=${XDG_CONFIG_HOME:-"$HOME/.config"}
if [ -r "$config_dir/superfile/env" ]; then
    . "$config_dir/superfile/env"
fi

export EDITOR="${EDITOR:-micro}"
export VISUAL="${VISUAL:-$EDITOR}"

exec spf "$@"
