#!/bin/sh
set -eu

export NEWT_COLORS='root=white,black
border=white,black
window=white,black
shadow=black,black
title=yellow,black
button=black,yellow
actbutton=black,brown
compactbutton=white,black
checkbox=white,black
actcheckbox=black,yellow
entry=white,black
label=white,black
listbox=white,black
actlistbox=black,yellow
sellistbox=white,black
actsellistbox=black,yellow
textbox=white,black
acttextbox=black,yellow
emptyscale=white,black
fullscale=black,yellow
helpline=white,black
roottext=white,black'

exec nmtui
