general {
    lock_cmd = pidof hyprlock >/dev/null || hyprlock --config ~/.config/hypr/hyprlock.conf
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 300
    on-timeout = pidof hyprlock >/dev/null && systemctl suspend
}
