background {
    monitor =
    path = ~/.local/share/backgrounds/dotfiles-wallpaper.png
    color = rgb(222226)
    blur_passes = 2
    blur_size = 5
    brightness = 0.55
    contrast = 0.9
    vibrancy = 0.15
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date '+%A, %d %B  %H:%M')"
    color = rgb(ffffff)
    font_size = 32
    font_family = JetBrainsMono Nerd Font
    position = 0, 160
    halign = center
    valign = center
}

label {
    monitor =
    text = Locked
    color = rgb(aaaaaa)
    font_size = 14
    font_family = JetBrainsMono Nerd Font
    position = 0, 112
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 320, 58
    outline_thickness = 1
    outer_color = rgb(ffbe6f)
    inner_color = rgb(38383c)
    font_color = rgb(ffffff)
    fade_on_empty = false
    hide_input = false
    placeholder_text = Password
    dots_size = 0.25
    dots_spacing = 0.25
    dots_center = true
    rounding = 0
    position = 0, 0
    halign = center
    valign = center
}
