#!/bin/sh

i=0
while [ "$i" -le 255 ]; do
    printf '\033[48;5;%sm%3d\033[0m ' "$i" "$i"
    if [ "$i" -eq 15 ] || { [ "$i" -gt 15 ] && [ "$(((i - 15) % 6))" -eq 0 ]; }; then
        printf '\n'
    fi
    i=$((i + 1))
done
